<template>
  <article class="course-tile card">
    <router-link :to="`/courses/${course.id}`" class="thumbnail" :class="`tone-${course.tone}`">
      <img :src="course.image" :alt="`${course.title} 강의 이미지`" /><span class="course-number">LR · {{ String(course.id).padStart(3,'0') }}</span>
      <span v-if="course.progress" class="progress-label">{{ course.progress }}% 학습</span>
    </router-link>
    <div class="course-body"><div class="tags"><span class="tag">{{ course.language }}</span><span class="tag gray">{{ course.level }}</span><span class="tag gray">{{ course.situation }}</span></div><router-link :to="`/courses/${course.id}`"><h3>{{ course.title }}</h3></router-link><p>{{ course.description }}</p><div class="course-meta"><span><Clock3 :size="14" />{{ course.duration }}</span><span><UsersRound :size="14" />{{ course.students }}명</span><button aria-label="강의 북마크"><Bookmark :size="16" /></button></div><div v-if="course.progress" class="progress"><span :style="`width:${course.progress}%`"></span></div></div>
  </article>
</template>
<script setup>import { Clock3,UsersRound,Bookmark } from '@lucide/vue'; defineProps({course:{type:Object,required:true}})</script>
<style scoped>.course-tile{overflow:hidden;transition:transform .22s ease,box-shadow .22s ease}.course-tile:hover{transform:translateY(-3px);box-shadow:var(--shadow-md)}.thumbnail{position:relative;height:158px;display:flex;align-items:center;justify-content:center;overflow:hidden;background:#dfe9e2}.thumbnail img{width:100%;height:100%;object-fit:cover;mix-blend-mode:multiply;opacity:.82;transition:transform .35s ease}.course-tile:hover .thumbnail img{transform:scale(1.04)}.tone-blue{background:#dfe8f4}.tone-amber{background:#f5ead4}.tone-purple{background:#ebe5f2}.tone-red{background:#f2dfda}.course-number,.progress-label{position:absolute;top:11px;padding:4px 8px;background:rgba(255,255,255,.9);border-radius:6px;font-family:var(--font-display);font-size:8px;font-weight:800;letter-spacing:.08em}.course-number{left:11px}.progress-label{right:11px;color:var(--forest-2)}.course-body{padding:17px}.tags{display:flex;gap:5px}.course-body h3{margin:12px 0 7px;font-size:15px;line-height:1.35}.course-body>p{height:38px;display:-webkit-box;overflow:hidden;color:var(--muted);font-size:10px;line-height:1.65;-webkit-line-clamp:2;-webkit-box-orient:vertical}.course-meta{display:flex;align-items:center;gap:13px;margin-top:14px;color:var(--muted);font-size:9px}.course-meta span{display:flex;align-items:center;gap:4px}.course-meta button{display:grid;place-items:center;margin-left:auto;color:var(--subtle);background:transparent}.progress{margin-top:13px}</style>
